# Generated by Django 3.0.8 on 2020-07-05 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, unique=True)),
                ('lastname', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogheader', models.CharField(max_length=100)),
                ('blog', models.CharField(max_length=500)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginApp.AppUser')),
            ],
        ),
    ]
